---

# Gerenciamento e Instalaçao de Pacotes

- name: Atualização do Sistema Operacional
  yum: 
    name: '*'
    state: latest
    update_cache: yes

- name: Instalação de Pacotes
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - net-tools
      - nmap
      - openssh-server

- name: Configurando Timezone
  file: src=/usr/share/zoneinfo/Brazil/West dest=/etc/localtime state=link force=yes

- name: Copiando Arquivo Backup
  copy: src=backup.tar.xz dest=/tmp/backup.tar.xz

- name: Copiando um Template
  template: src=motd dest=/tmp/motd force=yes owner=atila group=atila

- name: Instalação NGINX
  yum: name=nginx state=latest
  notify: Restart Nginx

...
